
language: python 
python: 
 - '3.7'

jobs:
  allow_failures:
     - language: python
      python: 3.8
      script:
      - python -c "print('Hi from Python!')"

    - language: node_js
      node_js: 12
      script:
      - node -e "console.log('Hi from NodeJS!')"

    - language: java
      jdk: openjdk8
      script:
      - javac -help

notifications:
  slack: saboogroupworkspace:tco87KFtlVfRyVKhQoaEfKQn#smartdms-dev