language: python 
python: 
- '3.7'
install:
- pip install -r requirements.txt
after_success:
- test $TRAVIS_BRANCH = “master” && zappa update
notifications:
  slack: saboogroupworkspace:tco87KFtlVfRyVKhQoaEfKQn#smartdms