language: python 
python: 
- '3.7'
install:
- pip install -r requirements.txt
script:
- echo "Hello before Zappa"
after_success:
- test $TRAVIS_BRANCH="master" && zappa update dev
notifications:
  slack: saboogroupworkspace:tco87KFtlVfRyVKhQoaEfKQn#smartdms-dev